name: Build and Push Lambda Image to ECR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to push to ECR"
        required: false
        default: "latest"
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile.lambda'
      - 'src/**'
      - 'requirements.txt'
      - 'pyproject.toml'

env:
  ECR_REPOSITORY: sticker-convert-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
        run: |
          docker build --platform linux/amd64 -f Dockerfile.lambda -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Optionally update Lambda function
        if: ${{ env.LAMBDA_FUNCTION_NAME != '' && env.LAMBDA_FUNCTION_NAME != null }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        run: |
          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --image-uri "$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"

# Setup secrets in GitHub repo settings → Secrets and variables → Actions:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_REGION (e.g., ap-southeast-1)
# Optional:
# - LAMBDA_FUNCTION_NAME (to auto-update after push)